### PR TITLE
Pin to Eslint 2.2.0

### LINKED ISSUE #112: Pin to Eslint 2.2.0 until 'estraverse-fb' bug is fixed
Until eslint/eslint#5476 is fixed, use ESLint v2.2.0.

The semver used in package.json is ^2.2.0 which causes ESLint v2.3.0 to be installed on clean installs.

### PR DESCRIPTION
**Pull request by ntwb**
Fixes #112

### CODE REVIEW

**Comment by Arcanemagus** [comment]
As this is only a devDependency, is there really a reason to do this?

**Comment by ntwb** [comment]
The previous build was failing due to the missing `estraverse-fb`, the stylelint 4.5.1 pull request failed because of this: https://travis-ci.org/AtomLinter/linter-stylelint/jobs/114470161

I'm not sure what the errors in Travis CI for this request are all about, Mac or Linux errors?

**Comment by Arcanemagus** [comment]
Oh boy, just looked at the build log... `stylelint` has _another_ dependency that tries to `eval()` which Atom doesn't allow at all.

Filed https://github.com/stylelint/stylelint/issues/891 to track what we are going to do about this.

**Comment by Arcanemagus** [comment]
Closing this in favor of #117 as both `stylelint` and `eslint` are causing issues right now.

**Pull request closed without merging**
