### PR TITLE
Remove 3rd party packages

### PR DESCRIPTION
**Pull request by 1000ch**
No longer maintained...

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Whoops, same changes were included in #122.

**Comment by 1000ch** [comment]
No worry, just my mistake.

**Comment by ntwb** [comment]
This change is a little disappointing, all 4 of those packages are still maintained.

**Comment by ntwb** [comment]
Nevermind, I just read #122 which adds the context that this was missing :)

**Pull request closed without merging**
