### PR TITLE
Update the readme

### LINKED ISSUE #131: Remove 3rd party stlyelint shared-configs from readme.md
3rd party shared-configs were removed in #122

The [readme.md #config](https://github.com/AtomLinter/linter-stylelint/blob/master/readme.md#config) section should be updated,

### PR DESCRIPTION
**Pull request by Arcanemagus**
* Remove references to old presets
* Update URLs
* Fix a few remark-lint issues

Fixes #131.

### CODE REVIEW

**Comment by ntwb** [comment]
Shouldn't the `Preset Config` option have been covered?

atom-linter-132

**Comment by Arcanemagus** [comment]
There [is no preset config](https://github.com/AtomLinter/linter-stylelint/blob/v2.0.1/lib/index.js#L9-L22).

You are hitting the Atom bug (feature?) where if something is in your `config.cson` Atom shows it... even if the plugin has no idea what it is.

**Comment by ntwb** [comment]
Right, tough one deciding if its a bug or a feature :smirk: 

Now I've completely removed the `linter-stylelint` package restarted and still have the `Use Preset` option, should this still be there?

atom-linter-132-2

**Comment by Arcanemagus** [comment]
Nope, that's another remnant, you should only have `Use standard` and `Disable when no config is found`. Removal of those options was one of the reasons this was a major release.

I wonder how much use a function left in there for a while removing those outdated settings would be...

**Comment by ntwb** [comment]
Fixed, I removed it manually from my `config.json` and restarted :+1:

**Pull request merged**
