### PR TITLE
Add specs

### PR DESCRIPTION
**Pull request by Arcanemagus**
Add some basic specs.

### CODE REVIEW

**Comment by Arcanemagus** [comment]
@1000ch if you want me to split the linting out into a different PR let me know.

Once this is landed we can enable CI builds which should get those "untested version" PR's to stop rolling in :wink:.

**Comment by 1000ch** [comment]
@Arcanemagus Awesome :+1:

**Comment by 1000ch** [comment]
Can I merge? (Do you have a plan to integrate with Travis CI?)

**Comment by Arcanemagus** [comment]
Merge away, just wanted to make sure the style changes were okay :wink:

Will be doing another PR shortly adding CI files.

**Comment by 1000ch** [comment]
>make sure the style changes were okay

LGTM :+1:

**Pull request merged**
