### PR TITLE
Updated stylelint and config-standard to latest

### LINKED ISSUE #317: Undefined rule rule-empty-line-before
Upgraded to stylelint 7.8.0 and stylelint-config-standard 16.0.0 and am receiving the error mentioned in the title. I do not have any modifications to the default ruleset. Is there an inner-dependency for this package that needs to be updated? I am seeing that as a valid rule on the stylelint website.

screen shot 2017-02-04 at 1 14 23 pm

### PR DESCRIPTION
**Pull request by SpainTrain**
- stylelint@7.8.0
- stylelint-config-standard@^16

closes #312
closes #313
closes #317

---
This change is [Reviewable](https://reviewable.io/reviews/atomlinter/linter-stylelint/316)

### CODE REVIEW

**Comment by SpainTrain** [comment]
Reviewed 1 of 1 files at r1.
Review status: all files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/atomlinter/linter-stylelint/316)*

**Comment by SpainTrain** [comment]
can anyone on @AtomLinter/linter-stylelint give this a quick review?

**Comment by 1000ch** [comment]
@SpainTrain 👍

**Comment by Arcanemagus** [comment]
Sorry about the delay, I've been busy with other things and this didn't get any attention. Thanks for taking care of this you two!

**Pull request merged**
