### PR TITLE
feat: sass linter

### PR DESCRIPTION
**Pull request by luketevers**
Updates base scopes to include sass since it's already built into stylelint.  It's working on my local, not sure what other testing was required. Adds note to readme to add sass to the list of lintable languages/extensions.

### CODE REVIEW

**Comment by contra** [comment]
@Arcanemagus Any objections to merging this?

**Comment by Arcanemagus** [comment]
We should probably have specs actually testing that linting the language works. That way we verify that it's _currently_ working, and make sure we don't break it in the future.

Some syntaxes have rules that [must be disabled](https://github.com/AtomLinter/linter-stylelint/blob/e550bfdb8ace3883be6244282c3aeb85c8293a64/lib/helpers.js#L270-L298), is SASS one of these?

Additionally the commit messages aren't following [Conventional Commits](https://www.conventionalcommits.org/en/v1.0.0/#summary), meaning the automated release process won't be able to properly parse them. This is causing CI to fail (which is why I hadn't even looked at this PR yet).

**Comment by luketevers** [comment]
Sorry I left this for so long, I didn't ever check commit requirements, got distracted and I didn't really notice this was still sitting here. AFAIK this is working on my local atom and I haven't seen any conflicts yet

**Comment by Arcanemagus** [comment]
> I didn't ever check commit requirements
If you run `npm install` in the project directory it should automatically install a `git` hook that runs the checks for you 😉.

> AFAIK this is working on my local atom and I haven't seen any conflicts yet

Yep, and we want to make sure it _stays_ working. Specs _should_ be as simple as the [specs for Less](https://github.com/AtomLinter/linter-stylelint/blob/e550bfdb8ace3883be6244282c3aeb85c8293a64/spec/linter-stylelint-spec.js#L201-L228) for example.

**Comment by luketevers** [comment]
Sounds good @Arcanemagus I'll get on that this weekend.

**Pull request closed without merging**
