### PR TITLE
Fix error & warn severity.

### PR DESCRIPTION
**Pull request by satazor**
See #55

### CODE REVIEW

**Comment by Arcanemagus** [comment]
Specs and everything? Thanks!

Any further changes or should I merge when CI builds finish?

**Comment by satazor** [comment]
No further changes! No problem! Took me a bit of time to know that the tests are run with apm test and not npm test, this was my first development in the atom environment.

**Comment by Arcanemagus** [comment]
Yea, Atom decided to roll their own wrapper around `npm` for a few reasons. Thanks for the PR!

**Comment by Arcanemagus** [comment]
Published in v1.7.1.

**Comment by satazor** [comment]
Thanks for the quick review and approval <3

**Comment by Arcanemagus** [comment]
I've been going through all the plugins publishing new versions to get the new `atom-linter` version that includes a workaround for OS X stripping the environment from all applications launched through the GUI :stuck_out_tongue:.

**Comment by satazor** [comment]
yeiiiii 

screenshot

**Pull request merged**
