### PR TITLE
Use the correct Stylelint instance

### LINKED ISSUE #440: Not using local version of stylelint
I'm getting the error `Undefined rule linebreaks` when linting but the rule was added in stylelint v9.4.0 (https://github.com/stylelint/stylelint/pull/3289). The linter-stylelint package is still at v9.3.0.

I've verified that my project's installed version is v9.7.1.

### PR DESCRIPTION
**Pull request by awcross**
Fixes #440

### CODE REVIEW

**Comment by swrobel** [comment]
@Arcanemagus would it be possible to get this merged?

**Comment by Arcanemagus** [comment]
As this currently is no, although it works it needs to be cleaned up some. Will be looking into it.

**Comment by Arcanemagus** [comment]
Replaced this with #553 since @awcross had never come back to this to fix the CI errors of their initial PR, and hadn't described their changes very well.

Thanks for taking the initiative to fix this though @awcross, and I'm sorry that it wasn't reviewed in a timely manner!

**Pull request closed without merging**
